# Name of the workflow as it appears in GitHub Actions UI
name: Deploy to GitHub Pages

# Define when this workflow should run
on:
  # Triggers the workflow on push events to master branch
  push:
    branches: ["master"]
  # Allows manual triggering of the workflow from GitHub UI
  workflow_dispatch:

# Set the required permissions for the workflow
permissions:
  contents: read       # Permission to read repository contents
  pages: write        # Permission to publish to GitHub Pages
  id-token: write     # Permission for authentication tokens

# Handle multiple workflow runs
concurrency:
  group: "pages"              # Group concurrent runs under "pages"
  cancel-in-progress: true    # Cancel in-progress runs when a new one starts

# Define the jobs to be executed
jobs:
  # First job: Build the Next.js application
  build:
    runs-on: ubuntu-latest    # Use Ubuntu as the runner environment
    steps:
      # Step 1: Check out the repository code
      - name: Checkout
        uses: actions/checkout@v4
      
      # Step 2: Set up Node.js environment
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"  # Use Node.js version 20
          cache: npm         # Cache npm dependencies for faster builds
      
      # Step 3: Configure GitHub Pages
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      # Step 4: Install project dependencies
      - name: Install dependencies
        run: npm ci          # Clean install of dependencies (stricter than npm install)
      
      # Step 5: Build the Next.js application
      - name: Build with Next.js
        run: npm run build
        env:
          NEXT_PUBLIC_BASE_PATH: /portfolio  # Set base path for routing
      
      # Step 6: Upload the built files as an artifact
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out        # Path to the static export directory

  # Second job: Deploy to GitHub Pages
  deploy:
    environment:
      name: github-pages     # Specify deployment environment
      url: ${{ steps.deployment.outputs.page_url }}  # Set deployment URL
    runs-on: ubuntu-latest   # Use Ubuntu for deployment
    needs: build            # Wait for build job to complete before running
    steps:
      # Deploy the built files to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4  # Use GitHub's deploy action 